const jwt = require('jsonwebtoken');
const User = require('../models/User.model');
const { jwtSecret, jwtRefreshSecret, jwtExpiry, jwtRefreshExpiry } = require('../config/env');

const generateTokens = (userId) => {
  const accessToken = jwt.sign({ sub: userId }, jwtSecret, { expiresIn: jwtExpiry });
  const refreshToken = jwt.sign({ sub: userId }, jwtRefreshSecret, { expiresIn: jwtRefreshExpiry });
  return { accessToken, refreshToken };
};

const signup = async ({ email, password }) => {
  // keySalt is auto-generated by the User model default
  const user = await User.create({ email, password });
  const keySalt = user.keySalt;
  return { user, keySalt, ...generateTokens(user._id.toString()) };
};

const login = async ({ email, password }) => {
  const user = await User.findOne({ email });
  if (!user || !(await user.comparePassword(password))) {
    const err = new Error('Invalid email or password');
    err.statusCode = 401;
    throw err;
  }
  const keySalt = user.keySalt;
  return { user, keySalt, ...generateTokens(user._id.toString()) };
};

const refresh = async (token) => {
  if (!token) {
    const err = new Error('Refresh token required');
    err.statusCode = 401;
    throw err;
  }

  let payload;
  try {
    payload = jwt.verify(token, jwtRefreshSecret);
  } catch {
    const err = new Error('Invalid or expired refresh token');
    err.statusCode = 401;
    throw err;
  }

  const user = await User.findById(payload.sub);
  if (!user) {
    const err = new Error('User not found');
    err.statusCode = 401;
    throw err;
  }

  const keySalt = user.keySalt;
  return { user, keySalt, ...generateTokens(user._id.toString()) };
};

module.exports = { signup, login, refresh };
